feels_log/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('', include('feels_logs.urls')),
    path('accounts/', include('allauth.urls')),
]

feels_logs/urls.py
from django.urls import path
from . import views

app_name = 'feels_logs'
urlpatterns = [
	#home page - blank string for default/home
	path('', views.index, name='index'),
	#evenets page
	path('events/', views.events, name='events'),
	#Detail page for a single event
	path('events/<int:event_id>/', views.event, name='event'),
	#page for adding a new event
	path('new_event/', views.new_event, name='new_event'),
	#page for adding a new entry
	path('new_entry/<int:event_id>/', views.new_entry, name='new_entry'),
	#page for editing an entry
	path('edit_entry/<int:entry_id>', views.edit_entry, name='edit_entry'),
	#page for deleting an entry
	path('delete_entry/<int:entry_id>', views.delete_entry, name='delete_entry'),
	#page for deleting an event
	path('delete_event/<int:event_id>', views.delete_event, name='delete_event')
]

users/urls.py
"""Defines URL patterns for users"""

from django.urls import path, include
from . import views

app_name = 'users'
urlpatterns = [
    #Include default auth urls
    path('', include('django.contrib.auth.urls')),
    #Registration page
    path('register/', views.register, name='register'),
]

feels_logs/models.py
from django.db import models
from django.contrib.auth.models import User


class Event(models.Model):
	"""A life event"""
	text = models.CharField(max_length=200)
	date_added = models.DateTimeField(auto_now_add=True)
	owner = models.ForeignKey(User, on_delete=models.CASCADE)
	
	def __str__(self):
		"""Return a string representation of the model."""
		return self.text

class Entry(models.Model):
	"""Entry from each emotion regarding the event"""
	event = models.ForeignKey(Event, on_delete=models.CASCADE) #entry references an event
	text = models.TextField()
	date_added = models.DateTimeField(auto_now_add=True)
	
	class Meta:
		verbose_name_plural = 'entries'
		
	def __str__(self):
		"""Return a string representation of the model"""
		if len(self.text)>50:
			return f"{self.text[:50]}..."
		else:
			return self.text

users/models.py
from django.db import models

# Create your models here.

feels_logs/forms.py
from django import forms
from .models import Event, Entry

class EventForm(forms.ModelForm):
	class Meta:
		model = Event
		fields = ['text']
		labels = {'text': ''}
		
class EntryForm(forms.ModelForm):
	class Meta:
		model = Entry
		fields = ['text']
		labels = {'text': 'Entry:'}
		widgets = {'text': forms.Textarea(attrs={'cols': 80})}

feels_logs/views.py
# Imports
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from .models import Event, Entry
from .forms import EventForm, EntryForm
from django.http import Http404

# Project views
# Home page
def index(request):
	"""The home page for Feels Logs"""
	return render(request, 'feels_logs/index.html')

# Checks that event belongs to current user
def check_topic_owner(request, event):
	if event.owner != request.user:
		raise Http404


@login_required #python decorator
def events(request):
	"""Show all events"""
	events = Event.objects.filter(owner=request.user).order_by('date_added')
	context = {'events': events}
	return render(request, 'feels_logs/events.html', context)

@login_required #python decorator	
def event(request, event_id):
	"""Show a single event and all its entires"""
	event = Event.objects.get(id=event_id)
	
	# Make sure the event belongs to the current user
	check_topic_owner(request, event)

	entries = event.entry_set.order_by('-date_added')
	context = {'event': event, 'entries': entries}
	return render(request, 'feels_logs/event.html', context)

@login_required #python decorator	
def new_event(request):
	"""Add a new event."""
	if request.method != 'POST':
		#No data submitted (no http post); create a blank form
		form = EventForm()
	else:
		#POST data submitted; process data
		form = EventForm(data=request.POST)
		if form.is_valid():
			new_event = form.save(commit=False)
			new_event.owner = request.user
			new_event.save()
			return redirect('feels_logs:events')
			
	#Display a blank or invalid form
	context = {'form' : form}
	return render(request, 'feels_logs/new_event.html', context)

@login_required #python decorator	
def new_entry(request, event_id):
	"""Add a new entry for a particular event."""
	event = Event.objects.get(id=event_id)
	
	# Make sure the event belongs to the current user
	check_topic_owner(request, event)
	
	if request.method != 'POST':
		#No data submitted; create a blank form.
		form = EntryForm()
	else:
		#POST data submitted; process data.
		form = EntryForm(data=request.POST)
		if form.is_valid():
			new_entry = form.save(commit=False)
			new_entry.event = event
			new_entry.save()
			return redirect('feels_logs:event', event_id=event_id)

	#Display a blank or invalid form
	context = {'event': event, 'form': form}
	return render(request, 'feels_logs/new_entry.html', context)


@login_required #python decorator
def edit_entry(request, entry_id):
	"""Edit an existing entry"""
	entry = Entry.objects.get(id=entry_id)
	event = entry.event

	"""if event.owner != request.user:
		raise Http404"""
	# Make sure the event belongs to the current user
	check_topic_owner(request, event)

	if request.method != 'POST':
		# initial request; pre-fill form with the current entry
		form = EntryForm(instance=entry)
	else:
		# POST data submitted; process data
		form = EntryForm(instance=entry, data=request.POST)
		if form.is_valid():
			form.save()
			return redirect('feels_logs:event', event_id=event.id)
	context = {'entry': entry, 'event': event, 'form': form}
	return render(request, 'feels_logs/edit_entry.html', context)

@login_required #python decorator
def delete_entry(request, entry_id):
	"""delete an existing entry"""
	entry = Entry.objects.get(id=entry_id)
	event = entry.event

	# Make sure the event belongs to the current user
	check_topic_owner(request, event)
	
	if request.method != 'POST':
		# initial request; pre-fill form with the current entry
		form = EntryForm(instance=entry)
	else:
		# Delete data submitted; process data
		entry.delete()
		return redirect('feels_logs:event', event_id=event.id)
	context = {'entry': entry, 'event': event, 'form': form}
	return render(request, 'feels_logs/delete_entry.html', context)

@login_required #python decorator	
def delete_event(request, event_id):
	"""Delete event - Delete a single event and all its entires"""
	event = Event.objects.get(id=event_id)
	
	# Make sure the event belongs to the current user
	check_topic_owner(request, event)

	#Gather event entries and order by date
	entries = event.entry_set.order_by('-date_added')

	#Delete all entries and the event
	if request.method == 'POST':
		for entry in entries:
			entry.delete()
		event.delete()
		return redirect('feels_logs:events')

	context = {'event': event, 'entries': entries}
	return render(request, 'feels_logs/delete_event.html', context)

users/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login
from django.contrib.auth.forms import UserCreationForm

# Viewes for the users app

def register(request):
    """Register new user."""
    if request.method != 'POST':
        #Display blank registration form
        form = UserCreationForm()
    else:
        #Process completed form
        form = UserCreationForm(data=request.POST)

        if form.is_valid():
            new_user = form.save()
            #Log the user in and then redirect to home page
            login(request, new_user)
            return redirect('feels_logs:index')
    #Display a blank or invalid form
    context = {'form': form}
    return render(request, 'registration/register.html', context)

feels_logs/templates/feels_logs/base.html
{% load bootstrap4 %}

<!doctype html>
<html lang="en">
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width", initial-scale=1, shrink-to-fit="no">
	<title>Events and Feelings</title>
	
	{% bootstrap_css %}
	{% bootstrap_javascript jquery='full' %}
</head>
<body>
	<nav class="navbar navbar-expand-md navbar-dark bg-dark mb-4 border">
		<a class="navbar-brand" href="{% url 'feels_logs:index' %}">Events and Feelings</a>

		<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-label="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
			<span class="navbar-toggler-icon"></span></button>
		<div class="collapse navbar-collapse" id="navbarCollapse">
			<ul class="navbar-nav mr-auto">
				{% if user.is_authenticated %}
					<li class="nav-item"><a class="nav-link" href="{% url 'feels_logs:events' %}">Events</a></li>
				{% endif %}
			</ul>
			<ul class="navbar-nav ml-auto">
				{% if user.is_authenticated %}
					<li class="nav-item">
						<span class="navbar-text"}">Hello, {{ user.username }}</span>
					</li>
					<li class="nav-item">
						<a class="nav-link" href="{% url 'users:logout' %}">Log out</a>
					</li>
				{% else %}
					<li class="nav-item">
						<a class="nav-link" href="{% url 'users:register' %}">Register</a>
					</li>
					<li class="nav-item">
						<a class="nav-link" href="{% url 'users:login' %}">Log in</a>
					</li>
				{% endif %}
			</ul>
		</div>
	</nav>
	<main role="main" class="container">
		<div class="pb-2 mb-2 border-bottom">
			{% block page_header %}{% endblock page_header %}
		</div>
		<div>
			{% block content %}{% endblock content %}
		</div>

	</main>
</body>
</html>

feels_logs/templates/feels_logs/base_old.html
<!--generate a link to index matching the URL pattern defined in feels_logs/urls.py-->
<p>
	<a href="{% url 'feels_logs:index' %}"> Log of many feels</a>
	<a href="{% url 'feels_logs:events' %}">Events</a>
	{% if user.is_authenticated %}
		Hello, {{ user.username }}
		<a href="{% url 'users:logout' %}">Log out</a>
	{% else %}
		<a href="{% url 'users:register' %}">Register</a>
		<a href="{% url 'users:login' %}">Log in</a>
	{% endif %}
</p>

<!--block tags. content will be a place holder for a child template-->
{% block content %}{% endblock content %}

feels_logs/templates/feels_logs/delete_entry.html
{% extends "feels_logs/base.html" %}
{% load bootstrap4 %}

{% block page_header %}
    <h3><a href="{% url 'feels_logs:event' event.id %}">{{ event }}</a></h3>
{% endblock page_header %}

{% block content %}
    
    <h5>Delete entry:</h5>

    <p>Are you sure you want to delete this entry?</p>

    <form action ="{% url 'feels_logs:delete_entry' entry.id %}" method='POST' class="form">
		{% csrf_token %}
		{% bootstrap_form form %}
        {% buttons %}
            <button name="submit" class="btn btn-primary">Delete Entry</button>
        {% endbuttons %}
    </form>
    

{% endblock content %}

feels_logs/templates/feels_logs/delete_event.html
{% extends "feels_logs/base.html" %}
{% load bootstrap4 %}

{% block page_header %}
    <h3>{{ event }}</h3>
{% endblock page_header %}

{% block content %}
    <h4>Delete event, "{{ event }}" ?</h4>
	{% for entry in entries %}
		<div class="card mb-3">
			<h4 class="card-header">
				{{ entry.date_added|date:'M d, Y H:i' }}
			</h4>
			<div class="card-body">
				{{ entry.text|linebreaks }}
			</div>
		</div>
	{% endfor %}

	<form method='POST' action ="{% url 'feels_logs:delete_event' event.id%}" class="form">
		{% csrf_token %}
		{% buttons %}
		Are you want to delete this event? 
			<button name="submit" class="btn btn-sm btn-danger outline">Delete</button>
			<a href="{% url 'feels_logs:events' %}">Cancel </a>
		{% endbuttons %}
	</form>


{% endblock content %}

feels_logs/templates/feels_logs/edit_entry.html
{% extends "feels_logs/base.html" %}
{% load bootstrap4 %}

{% block page_header %}
    <h3><a href="{% url 'feels_logs:event' event.id %}">{{ event }}</a></h3>
{% endblock page_header %}

{% block content %}
    
    <h5>Edit entry:</h5>

    <form action ="{% url 'feels_logs:edit_entry' entry.id %}" method='post' class="form">
		{% csrf_token %}
		{% bootstrap_form form %}
        {% buttons %}
            <button name="submit" class="btn btn-primary">Update Entry</button>
        {% endbuttons %}
	</form>


{% endblock content %}

feels_logs/templates/feels_logs/event.html
{% extends "feels_logs/base.html" %}

{% block page_header %}
    <h3>{{ topic }}</h3>
{% endblock page_header %}

{% block content %}
	<p>
		<a href="{% url 'feels_logs:new_entry' event.id %}">Add new entry</a>
	</p>

	{% for entry in entries %}
		<div class="card mb-3">
			<h4 class="card-header">
				{{ entry.date_added|date:'M d, Y H:i' }}
				<small><a href="{% url 'feels_logs:edit_entry' entry.id %}">edit</a></small>
				<small><a href="{% url 'feels_logs:delete_entry' entry.id %}">delete</a></small>
			</h4>
			<div class="card-body">
				{{ entry.text|linebreaks }}
			</div>
		</div>
	{% empty %}
		<p>There are no entries for this event yet.</p>
	{% endfor %}

{% endblock content %}

feels_logs/templates/feels_logs/events.html
{% extends "feels_logs/base.html" %}

{% block page_header %}
    <h1>Events</h1>
{% endblock page_header %}

{% block content %}
	<div class="container">
		<ul class="list-group">
			{% for event in events %}
				<li style="list-style-type:none" class="list-group-item d-flex justify-content-between align-items-center">
					<h4>{{ event }}</h4>
					<span>
						<a class="btn btn-outline-primary btn-sm" href="{% url 'feels_logs:event' event.id %}" role="button">Add new entry</a>
						<a class="btn btn-outline-danger btn-sm" href="{% url 'feels_logs:delete_event' event.id %}" role="button">Delete Event</a>
					</span>
				</li>
			{% empty %}
				<li><h3>No events have been added yet.</h3></li>
			{% endfor %}
		</ul>
	</div>
	<br>
	<div class="container">
		<a class="btn btn-primary btn-sm" href="{% url 'feels_logs:new_event' %}">Add new event</a>
	</div>
{% endblock content %}

feels_logs/templates/feels_logs/index.html
{% extends "feels_logs/base.html" %}

{% block page_header %}

	<div class="jumbotron">
		<h1 class="display-3">Events and Feelings</h1>
		{% if user.is_authenticated %}
			<div>
				<p>Welcome in, {{ user.username }}.  What's the happs?</p>
				<a class="btn btn-lg btn-primary" href="{% url 'feels_logs:events' %}" role="button">Add new event &raquo;</a>
			</div>
		{% else %}
			<p class="lead">Log snapshots of your life events.  Track how your feelings have changed as each event progresses.</p>
			<a class="btn btn-lg btn-primary" href="{% url 'users:register' %}" role="button">Register &raquo;</a>
		{% endif %}
	</div>

{% endblock page_header %}

feels_logs/templates/feels_logs/new_entry.html
{% extends "feels_logs/base.html" %}
{% load bootstrap4 %}

{% block page_header %}
    <h3><a href="{% url 'feels_logs:event' event.id %}">{{ event }}</a></h3>
{% endblock page_header %}


{% block content %}
	
	<h5>Add a new entry:</h5>

	<form action ="{% url 'feels_logs:new_entry' event.id %}" method='post' class="form">
		{% csrf_token %}
		{% bootstrap_form form %}
        {% buttons %}
            <button name="submit" class="btn btn-primary">Add entry</button>
        {% endbuttons %}
	</form>
	
{% endblock content %}

feels_logs/templates/feels_logs/new_event.html
{% extends "feels_logs/base.html" %}
{% load bootstrap4 %}

{% block page_header %}
    <h4>Add a new event:</h4>
{% endblock page_header %}

{% block content %}
	
	<form method = "post" action = "{% url 'feels_logs:new_event' %}" class="form">
		{% csrf_token %}
		{% bootstrap_form form %}
		{% buttons %}
			<button name="submit" class="btn btn-primary">Add Event</button>
		{% endbuttons %}
	</form>

{% endblock content %}

feels_logs/templates/feels_logs/template.html
{% extends "feels_logs/base.html" %}

{% block page_header %}
    <h1>TITLE</h1>
{% endblock page_header %}

{% block content %}
    
    <p>STUFF!</p>

{% endblock content %}